### ISSUE TITLE
Camera not work

### ISSUE THREAD

**Issue by entony80** [sonyxperiadev/device-sony-flamingo#19]
Camera exists in application system but does not appear in the drawer, third-party applications do not work for the Camera . You can resolve this problem? Thanks for your work

**Comment by jerpelea** [comment]
camera is not implemented yet

**Comment by Kaor** [comment]
why ?
i just bought many E3, it's unfair !

**Comment by jerpelea** [comment]
it will come !

**Comment by Kaor** [comment]
YES !
